### ISSUE TITLE
Cannot perfom migration

### ISSUE THREAD

**Issue by CynthiaKamau** [mbbu/sample_management_system#12]
File "migrations/env.py", line 30, in <module>
    'SQLALCHEMY_DATABASE_URI').replace('%', '%%'))
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by jeffkim207** [comment]
The above issue is caused by flask-migrate(alembic) not finding target meta-data for the models. I have a **temporary** workaround to the issue as I look into a long-term solution on the same. 

Whenever you want to make a migration, in the database.py file, under the migrate_db() function alter the return type to be as shown below;
```
models = [
            Role, User, Theme, Sample,
            Box, Tray, Rack,
            Chamber, Freezer, Laboratory, Publication
        ]

for model in models:
     return model
```

For now, just pull the most current change from **develop** and issue will be fixed.

**Comment by jeffkim207** [comment]
> The above issue is caused by flask-migrate(alembic) not finding target meta-data for the models. I have a **temporary** workaround to the issue as I look into a long-term solution on the same.
> 
> Whenever you want to make a migration, in the database.py file, under the migrate_db() function alter the return type to be as shown below;
> 
> ```
> models = [
>             Role, User, Theme, Sample,
>             Box, Tray, Rack,
>             Chamber, Freezer, Laboratory, Publication
>         ]
> 
> for model in models:
>      return model
> ```
> 
> For now, just pull the most current change from **develop** and issue will be fixed.

I have resolved the issue by creating an alternative function, specifically for exporting the models' metadata.

**Comment by CynthiaKamau** [comment]
Not working for me

**Comment by CynthiaKamau** [comment]
Now its worked

**Comment by jeffkim207** [comment]
Great! @CynthiaKamau you can close the issue now if it's fully resolved
